create database join_table;

use join_table;

-- LOAD DATA-SET IN SQL WORKSET:

-- STEP:01 SELECT DATABASE AND RIGHT CLICK ON DATABASE.
-- STEP:02 SELECT "TABLE IMPORT DATA WIZARD" ( THIS WORK ONLY CSV FILE OR JSON FILE ).
-- STEP:03 GIVE PATH FOR WHERE YOU CAN SAVE CSV OR JSON FILE.
-- STEP:04 CLICK "NEXT" BUTTON UPTO FINISH PROCESS.

SELECT * FROM table1;
SELECT * FROM table2;
SELECT * FROM table3;

-- 01 INNER QUERY SYNTAX(01) :-
SELECT * FROM TABLE1 INNER JOIN TABLE2 ON TABLE1.STUDENT_ID = TABLE2.STUDENT_ID;
-- 02 INNER JOIN SYNTAX(02) :-
SELECT TABLE1.STUDENT_ID , STUDENT_NAME , CITY FROM TABLE1 INNER JOIN TABLE2 ON TABLE1.STUDENT_ID = TABLE2.STUDENT_ID;
-- 03 LEFT QUERY SYNTAX (01) :-
SELECT * FROM TABLE1 LEFT JOIN TABLE2 ON TABLE1.STUDENT_ID = TABLE2.STUDENT_ID;
-- 04 LEFT QUERY SYNTAX (02) :-
SELECT TABLE1.STUDENT_ID , STUDENT_NAME , GENDER FROM TABLE1 LEFT JOIN TABLE2 ON TABLE1.STUDENT_ID = TABLE2.STUDENT_ID;
-- 05 LEFT QUERY SYNTAX (03) :-
SELECT A.STUDENT_ID , STUDENT_NAME , GENDER FROM TABLE1 AS A LEFT JOIN TABLE2 AS B ON A.STUDENT_ID = B.STUDENT_ID;
-- 06 RIGHT QUERY SYNTAX (01) :-
SELECT * FROM TABLE1 RIGHT JOIN TABLE2 ON TABLE1.STUDENT_ID = TABLE2.STUDENT_ID ;
-- 07 RIGHT QUERY SYNTAX (02) :-
SELECT TABLE1.STUDENT_ID , STUDENT_NAME , CITY FROM TABLE1 RIGHT JOIN TABLE2 ON TABLE1.STUDENT_ID = TABLE2.STUDENT_ID;
-- 08 CROSS-JOIN SYNTAX (01) :-
SELECT * FROM TABLE1 CROSS JOIN TABLE2 ;

-- 09 INNER-JOIN MULTIPLE TABLE :-
SELECT * FROM TABLE1 AS A INNER JOIN TABLE2 AS B ON A.STUDENT_ID  = B.STUDENT_ID INNER JOIN TABLE3 AS C ON B.STUDENT_ID = C.STUDENT_ID;
-- 10 LEFT-JOIN MULTIPLE TABLE :-
SELECT * FROM TABLE1 AS A LEFT JOIN TABLE2 AS B ON A.STUDENT_ID = B.STUDENT_ID LEFT JOIN TABLE3 AS C ON B.STUDENT_ID = C.STUDENT_ID;
-- 11 RIGHT-JOIN MULTIPLE TABLE :-
SELECT * FROM TABLE1 AS A RIGHT JOIN TABLE2 AS B ON A.STUDENT_ID = B.STUDENT_ID RIGHT JOIN TABLE3 AS C ON B.STUDENT_ID = C.STUDENT_ID;
-- 12 LEFT-JOIN MULTIPLE TABLE :-
SELECT * FROM TABLE1 CROSS JOIN TABLE2 CROSS JOIN TABLE3;
-- 13 INNER JOIN MULTIPLE TABLE :-
SELECT TABLE1.STUDENT_ID , STUDENT_NAME , MARKS , GENDER , CITY , TABLE2.STUDENT_ID , TABLE3.STUDENT_ID FROM TABLE1 INNER JOIN TABLE2 
ON TABLE1.STUDENT_ID = TABLE2.STUDENT_ID INNER JOIN TABLE3 ON TABLE2.STUDENT_ID = TABLE3.STUDENT_ID;

-- 14 ( 29.346) EXTRA FUNCTION = "ROUND" :-
SELECT ROUND(29.346 ,2);
SELECT ROUND(29.346 ,-1);
SELECT ROUND(29.346 ,-2);

-- 15 ( 29.346) EXTRA FUNCTION = "CEIL" :-
SELECT CEIL(29.123);

-- 14 ( 29.346) EXTRA FUNCTION = "FLOOR" :-
SELECT FLOOR(29.123);

-- 15 YOU HAVE TO FIND YOUR AGE IN YEARS :-
SELECT round(datediff(current_date(),"2004-05-12")/365,0) as AGE;

-- 16 DIFFERENCE BETWEEEN BOTH DATE :-
SELECT datediff("2023-08-07","2023-08-01") as DIFF_BOTH_DATE;